services:
  postgres:
    image: postgres:latest
    container_name: playpals-postgres
    environment:
      POSTGRES_USER: playpals-admin
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: playpals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: